import { Provider } from "@/Provider";
import "./globals.css";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import AppBar from "./components/appbar";
import Sidebar from "./components/sidebar";
import CreateNots from "./components/CreateNots";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/lib/auth.config";
import RecoilContextProvider from "@/Provider/recoil";
import Navbar from "./components/Navbar";
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  adjustFontFallback: false,
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  console.log(session);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster position="top-left" />
        <Provider>
          <RecoilContextProvider>
            <Sidebar>
              {session && (
                <main className="w-full flex flex-col items-center h-full">
                  <CreateNots />
                  {children}
                </main>
              )}
            </Sidebar>
          </RecoilContextProvider>
        </Provider>
      </body>
    </html>
  );
}
